import styles from "../styles/pages/index.module.scss";
import { type NextPage } from "next";
import Head from "next/head";
import Link from "next/link";


const Home: NextPage = () => {

  return (
    <>
      <Head>
        <title>Library</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
        <div className={styles.container}>
          <h1 className={styles.title}>
            <span className={styles.pinkSpan}>Library</span> App
          </h1>
          <p>A collection of examples recreated and more.</p>
        </div>
      </main>
    </>
  );
};

export default Home;
