import { type NextPage } from "next";
import Head from "next/head";
import { createClient } from "next-sanity";

type project = {
  projects: {
    _id: string;
    name: string;
  }[];
}

export const ProjectPage: NextPage = ({ projects }: project) => {
  return (
    <>
      <Head>
        <title>Project</title>
        <meta name='description' content='Generated by create-t3-app' />
        <link rel='icon' href='/favicon.ico' />
      </Head>
      <main>
      <section>
        <header>
          <h1>Projects</h1>
          <p>All projects I have worked on in the past time</p>
        </header>
        {projects.length > 0 && (
          <ul>
            {projects?.map((project) => (
              <li key={project._id}>{project.name}</li>
            ))}
          </ul>
        )}
        {!projects.length && <p>No projects to show</p>}
        {projects.length > 0 && (
          <div>
            <pre>{JSON.stringify(projects, null, 2)}</pre>
          </div>
        )}
      </section>
      </main>
    </>
  );
};

const client = createClient({
  projectId: process.env.NEXT_PUBLIC_SANITY_PROJECT_ID,
  dataset: process.env.NEXT_PUBLIC_SANITY_DATASET,
  useCdn: false,
});

export async function getStaticProps() {
  const projects = await client.fetch(`*[_type == "project"]`);

  return {
    props: {
      projects,
    },
  };
}

export default ProjectPage;
